#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    uint32_t serial_baudrate;
    uint8_t external_speaker_value;
    uint16_t external_display_value;
    uint8_t clear_display;
    uint8_t output_power;
    uint8_t pmic_button;
    uint8_t internal_imu;
    uint8_t internal_rtc;
    uint8_t internal_mic;
    uint8_t internal_spk;
    uint8_t external_imu;
    uint8_t external_rtc;
    uint8_t disable_rtc_irq;
    uint8_t led_brightness;
    int fallback_board;
} m5u_config_t;

typedef struct {
    int x;
    int y;
    int max_width;
    int max_height;
    int off_x;
    int off_y;
    float scale_x;
    float scale_y;
    int datum;
} m5u_image_options_t;

bool m5u_begin(void);
bool m5u_begin_with_config(const m5u_config_t* config);
void m5u_update(void);
void m5u_delay_ms(uint32_t ms);
uint32_t m5u_millis(void);
uint32_t m5u_micros(void);
uint32_t m5u_get_update_msec(void);
size_t m5u_heap_get_free_size(uint32_t caps);
size_t m5u_heap_get_largest_free_block(uint32_t caps);
int m5u_get_board(void);
int m5u_get_pin(int name);
bool m5u_set_primary_display_index(size_t index);
bool m5u_set_primary_display_type(int kind);
bool m5u_set_primary_display_types(const int* kinds, size_t len);
void m5u_set_log_display_index(size_t index);
void m5u_set_log_display_type(int kind);
void m5u_set_log_display_types(const int* kinds, size_t len);
void m5u_set_touch_button_height(uint16_t pixel);
void m5u_set_touch_button_height_by_ratio(uint8_t ratio);
uint16_t m5u_get_touch_button_height(void);

bool m5u_io_expander_available(size_t index);
bool m5u_io_expander_set_direction(size_t index, uint8_t pin, bool output);
bool m5u_io_expander_enable_pull(size_t index, uint8_t pin, bool enable);
bool m5u_io_expander_set_pull_mode(size_t index, uint8_t pin, bool pull_up);
bool m5u_io_expander_set_high_impedance(size_t index, uint8_t pin, bool enable);
bool m5u_io_expander_get_write_value(size_t index, uint8_t pin);
bool m5u_io_expander_digital_write(size_t index, uint8_t pin, bool level);
bool m5u_io_expander_digital_read(size_t index, uint8_t pin);
bool m5u_io_expander_reset_irq(size_t index);
bool m5u_io_expander_disable_irq(size_t index);
bool m5u_io_expander_enable_irq(size_t index);
bool m5u_pi4ioe5v6408_begin(void);
bool m5u_pi4ioe5v6408_set_direction(uint8_t pin, bool output);
bool m5u_pi4ioe5v6408_enable_pull(uint8_t pin, bool enable);
bool m5u_pi4ioe5v6408_set_pull_mode(uint8_t pin, bool pull_up);
bool m5u_pi4ioe5v6408_set_high_impedance(uint8_t pin, bool enable);
bool m5u_pi4ioe5v6408_get_write_value(uint8_t pin);
bool m5u_pi4ioe5v6408_digital_write(uint8_t pin, bool level);
bool m5u_pi4ioe5v6408_digital_read(uint8_t pin);
void m5u_pi4ioe5v6408_reset_irq(void);
void m5u_pi4ioe5v6408_disable_irq(void);
void m5u_pi4ioe5v6408_enable_irq(void);

void m5u_i2c_set_port(int bus, int port_num, int pin_sda, int pin_scl);
bool m5u_i2c_begin(int bus);
bool m5u_i2c_begin_with_port(int bus, int port_num, int pin_sda, int pin_scl);
bool m5u_i2c_release(int bus);
bool m5u_i2c_is_enabled(int bus);
int m5u_i2c_get_port(int bus);
int m5u_i2c_get_sda(int bus);
int m5u_i2c_get_scl(int bus);
bool m5u_i2c_start(int bus, uint8_t address, bool read, uint32_t freq);
bool m5u_i2c_restart(int bus, uint8_t address, bool read, uint32_t freq);
bool m5u_i2c_stop(int bus);
bool m5u_i2c_write_byte(int bus, uint8_t data);
bool m5u_i2c_write(int bus, const uint8_t* data, size_t length);
bool m5u_i2c_read(int bus, uint8_t* result, size_t length, bool last_nack);
bool m5u_i2c_write_register(int bus, uint8_t address, uint8_t reg, const uint8_t* data, size_t length, uint32_t freq);
bool m5u_i2c_read_register(int bus, uint8_t address, uint8_t reg, uint8_t* result, size_t length, uint32_t freq);
bool m5u_i2c_write_register8(int bus, uint8_t address, uint8_t reg, uint8_t data, uint32_t freq);
uint8_t m5u_i2c_read_register8(int bus, uint8_t address, uint8_t reg, uint32_t freq);
bool m5u_i2c_bit_on(int bus, uint8_t address, uint8_t reg, uint8_t data, uint32_t freq);
bool m5u_i2c_bit_off(int bus, uint8_t address, uint8_t reg, uint8_t data, uint32_t freq);
void m5u_i2c_scan(int bus, bool* result, uint32_t freq);
bool m5u_i2c_scan_address(int bus, uint8_t address, uint32_t freq);

int m5u_display_width(void);
int m5u_display_height(void);
void m5u_display_fill_screen(uint16_t color);
void m5u_display_set_cursor(int x, int y);
void m5u_display_set_text_size(int size);
void m5u_display_set_text_color(uint16_t fg, uint16_t bg);
void m5u_display_print(const char* text);
void m5u_display_println(const char* text);
void m5u_display_draw_line(int x0, int y0, int x1, int y1, uint16_t color);
void m5u_display_draw_rect(int x, int y, int w, int h, uint16_t color);
void m5u_display_fill_rect(int x, int y, int w, int h, uint16_t color);
void m5u_display_draw_circle(int x, int y, int r, uint16_t color);
void m5u_display_fill_circle(int x, int y, int r, uint16_t color);
void m5u_display_set_rotation(int rotation);
int m5u_display_get_rotation(void);
void m5u_display_set_brightness(uint8_t brightness);
uint8_t m5u_display_get_brightness(void);
void m5u_display_sleep(void);
void m5u_display_wakeup(void);
void m5u_display_power_save(bool enable);
void m5u_display_invert_display(bool invert);
bool m5u_display_get_invert(void);
void m5u_display_set_swap_bytes(bool swap);
bool m5u_display_get_swap_bytes(void);
void m5u_display_set_color_depth(int depth);
int m5u_display_get_color_depth(void);
void m5u_display_set_addr_window(int x, int y, int w, int h);
void m5u_display_set_window(int xs, int ys, int xe, int ye);
void m5u_display_begin_transaction(void);
void m5u_display_end_transaction(void);
uint32_t m5u_display_get_start_count(void);
int m5u_display_get_scan_line(void);
void m5u_display_set_raw_color(uint32_t color);
uint32_t m5u_display_get_raw_color(void);
void m5u_display_write_color(uint16_t color, uint32_t length);
void m5u_display_draw_pixel_current(int x, int y);
void m5u_display_write_pixel_current(int x, int y);
void m5u_display_write_fill_rect(int x, int y, int w, int h, uint16_t color);
void m5u_display_write_fill_rect_preclipped(int x, int y, int w, int h, uint16_t color);
void m5u_display_push_block(uint16_t color, uint32_t length);
void m5u_display_progress_bar(int x, int y, int w, int h, uint8_t value);
void m5u_display_push_state(void);
void m5u_display_pop_state(void);
void m5u_display_set_epd_fastest(void);
void m5u_display_set_epd_mode(int mode);
void m5u_display_set_text_scroll(bool scroll);
bool m5u_display_set_font(int font);
void m5u_display_start_write(void);
void m5u_display_end_write(void);
void m5u_display_display(void);
void m5u_display_display_region(int x, int y, int w, int h);
bool m5u_display_display_busy(void);
void m5u_display_wait_display(void);
bool m5u_display_has_palette(void);
uint32_t m5u_display_get_palette_count(void);
bool m5u_display_is_readable(void);
bool m5u_display_is_epd(void);
bool m5u_display_is_bus_shared(void);
void m5u_display_set_auto_display(bool enable);
void m5u_display_init_dma(void);
void m5u_display_wait_dma(void);
bool m5u_display_dma_busy(void);
int m5u_display_get_cursor_x(void);
int m5u_display_get_cursor_y(void);
int m5u_display_font_height(void);
uint32_t m5u_display_get_base_color(void);
void m5u_display_set_base_color(uint32_t color);
void m5u_display_set_color(uint16_t color);
void m5u_display_set_text_wrap(bool wrap_x, bool wrap_y);
void m5u_display_set_text_datum(int datum);
int m5u_display_draw_string(const char* text, int x, int y);
int m5u_display_draw_center_string(const char* text, int x, int y);
int m5u_display_draw_right_string(const char* text, int x, int y);
int m5u_display_draw_number(int value, int x, int y);
int m5u_display_draw_float(float value, uint8_t decimals, int x, int y);
int m5u_display_draw_char(uint16_t codepoint, int x, int y);
void m5u_display_draw_pixel(int x, int y, uint16_t color);
void m5u_display_write_pixel(int x, int y, uint16_t color);
void m5u_display_draw_fast_hline(int x, int y, int w, uint16_t color);
void m5u_display_write_fast_hline(int x, int y, int w, uint16_t color);
void m5u_display_draw_fast_vline(int x, int y, int h, uint16_t color);
void m5u_display_write_fast_vline(int x, int y, int h, uint16_t color);
void m5u_display_draw_round_rect(int x, int y, int w, int h, int r, uint16_t color);
void m5u_display_fill_round_rect(int x, int y, int w, int h, int r, uint16_t color);
void m5u_display_draw_triangle(int x0, int y0, int x1, int y1, int x2, int y2, uint16_t color);
void m5u_display_fill_triangle(int x0, int y0, int x1, int y1, int x2, int y2, uint16_t color);
void m5u_display_draw_ellipse(int x, int y, int rx, int ry, uint16_t color);
void m5u_display_fill_ellipse(int x, int y, int rx, int ry, uint16_t color);
void m5u_display_draw_arc(int x, int y, int r0, int r1, float angle0, float angle1, uint16_t color);
void m5u_display_fill_arc(int x, int y, int r0, int r1, float angle0, float angle1, uint16_t color);
void m5u_display_draw_ellipse_arc(int x, int y, int r0x, int r1x, int r0y, int r1y, float angle0, float angle1, uint16_t color);
void m5u_display_fill_ellipse_arc(int x, int y, int r0x, int r1x, int r0y, int r1y, float angle0, float angle1, uint16_t color);
void m5u_display_draw_bezier3(int x0, int y0, int x1, int y1, int x2, int y2, uint16_t color);
void m5u_display_draw_bezier4(int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3, uint16_t color);
void m5u_display_draw_smooth_line(int x0, int y0, int x1, int y1, uint16_t color);
void m5u_display_draw_wide_line(int x0, int y0, int x1, int y1, float radius, uint16_t color);
void m5u_display_draw_wedge_line(int x0, int y0, int x1, int y1, float r0, float r1, uint16_t color);
void m5u_display_draw_gradient_line(int x0, int y0, int x1, int y1, uint16_t start_color, uint16_t end_color);
void m5u_display_draw_spot(int x, int y, float radius, uint16_t color);
void m5u_display_fill_smooth_circle(int x, int y, int r, uint16_t color);
void m5u_display_fill_smooth_round_rect(int x, int y, int w, int h, int r, uint16_t color);
void m5u_display_fill_gradient_rect(int x, int y, int w, int h, uint16_t start_color, uint16_t end_color, int style);
void m5u_display_flood_fill(int x, int y, uint16_t color);
void m5u_display_set_scroll_rect(int x, int y, int w, int h);
void m5u_display_set_scroll_rect_color(int x, int y, int w, int h, uint16_t color);
void m5u_display_get_scroll_rect(int* x, int* y, int* w, int* h);
void m5u_display_clear_scroll_rect(void);
void m5u_display_scroll(int dx, int dy);
int m5u_display_text_width(const char* text);
int m5u_display_text_length(const char* text, int width);
int m5u_display_get_text_datum(void);
int m5u_display_font_width(void);
void m5u_display_set_text_padding(uint32_t padding);
uint32_t m5u_display_get_text_padding(void);
float m5u_display_get_text_size_x(void);
float m5u_display_get_text_size_y(void);
void m5u_display_set_clip_rect(int x, int y, int w, int h);
void m5u_display_get_clip_rect(int* x, int* y, int* w, int* h);
void m5u_display_clear_clip_rect(void);
uint32_t m5u_display_color888(uint8_t r, uint8_t g, uint8_t b);
void m5u_display_set_pivot(float x, float y);
float m5u_display_get_pivot_x(void);
float m5u_display_get_pivot_y(void);
bool m5u_display_push_image_rgb565(int x, int y, int w, int h, const uint16_t* data);
bool m5u_display_push_image_rgb565_transparent(int x, int y, int w, int h, const uint16_t* data, uint16_t transparent);
uint16_t m5u_display_read_pixel(int x, int y);
bool m5u_display_read_rect_rgb565(int x, int y, int w, int h, uint16_t* data);
void m5u_display_copy_rect(int dst_x, int dst_y, int w, int h, int src_x, int src_y);
bool m5u_display_draw_image(int format, const uint8_t* data, size_t len, const m5u_image_options_t* options);
bool m5u_display_draw_image_file(int format, const char* path, const m5u_image_options_t* options);
void m5u_display_qrcode(const char* text, int x, int y, int width, uint8_t version, bool margin);
int m5u_display_count(void);
int m5u_display_index_for_kind(int kind);
int m5u_display_index_for_kinds(const int* kinds, size_t len);
int m5u_display_width_at(int index);
int m5u_display_height_at(int index);
void m5u_display_fill_screen_at(int index, uint16_t color);
void m5u_display_set_cursor_at(int index, int x, int y);
void m5u_display_set_text_size_at(int index, int size);
void m5u_display_set_text_color_at(int index, uint16_t fg, uint16_t bg);
int m5u_display_get_rotation_at(int index);
void m5u_display_set_rotation_at(int index, int rotation);
void m5u_display_set_brightness_at(int index, uint8_t brightness);
uint8_t m5u_display_get_brightness_at(int index);
void m5u_display_sleep_at(int index);
void m5u_display_wakeup_at(int index);
void m5u_display_power_save_at(int index, bool enable);
void m5u_display_invert_display_at(int index, bool invert);
bool m5u_display_get_invert_at(int index);
void m5u_display_set_swap_bytes_at(int index, bool swap);
bool m5u_display_get_swap_bytes_at(int index);
void m5u_display_set_color_depth_at(int index, int depth);
int m5u_display_get_color_depth_at(int index);
void m5u_display_set_addr_window_at(int index, int x, int y, int w, int h);
void m5u_display_set_window_at(int index, int xs, int ys, int xe, int ye);
void m5u_display_begin_transaction_at(int index);
void m5u_display_end_transaction_at(int index);
uint32_t m5u_display_get_start_count_at(int index);
int m5u_display_get_scan_line_at(int index);
void m5u_display_set_raw_color_at(int index, uint32_t color);
uint32_t m5u_display_get_raw_color_at(int index);
void m5u_display_write_color_at(int index, uint16_t color, uint32_t length);
void m5u_display_draw_pixel_current_at(int index, int x, int y);
void m5u_display_write_pixel_current_at(int index, int x, int y);
void m5u_display_write_fill_rect_at(int index, int x, int y, int w, int h, uint16_t color);
void m5u_display_write_fill_rect_preclipped_at(int index, int x, int y, int w, int h, uint16_t color);
void m5u_display_push_block_at(int index, uint16_t color, uint32_t length);
void m5u_display_progress_bar_at(int index, int x, int y, int w, int h, uint8_t value);
void m5u_display_push_state_at(int index);
void m5u_display_pop_state_at(int index);
void m5u_display_set_color_at(int index, uint16_t color);
uint32_t m5u_display_get_base_color_at(int index);
void m5u_display_set_base_color_at(int index, uint32_t color);
int m5u_display_get_cursor_x_at(int index);
int m5u_display_get_cursor_y_at(int index);
void m5u_display_start_write_at(int index);
void m5u_display_end_write_at(int index);
void m5u_display_display_at(int index);
void m5u_display_display_region_at(int index, int x, int y, int w, int h);
bool m5u_display_display_busy_at(int index);
void m5u_display_wait_display_at(int index);
bool m5u_display_has_palette_at(int index);
uint32_t m5u_display_get_palette_count_at(int index);
bool m5u_display_is_readable_at(int index);
bool m5u_display_is_epd_at(int index);
bool m5u_display_is_bus_shared_at(int index);
void m5u_display_set_auto_display_at(int index, bool enable);
void m5u_display_init_dma_at(int index);
void m5u_display_wait_dma_at(int index);
bool m5u_display_dma_busy_at(int index);
void m5u_display_print_at(int index, const char* text);
void m5u_display_println_at(int index, const char* text);
int m5u_display_draw_string_at(int index, const char* text, int x, int y);
int m5u_display_draw_center_string_at(int index, const char* text, int x, int y);
int m5u_display_draw_right_string_at(int index, const char* text, int x, int y);
int m5u_display_draw_number_at(int index, int value, int x, int y);
int m5u_display_draw_float_at(int index, float value, uint8_t decimals, int x, int y);
int m5u_display_draw_char_at(int index, uint16_t codepoint, int x, int y);
void m5u_display_draw_line_at(int index, int x0, int y0, int x1, int y1, uint16_t color);
void m5u_display_draw_rect_at(int index, int x, int y, int w, int h, uint16_t color);
void m5u_display_fill_rect_at(int index, int x, int y, int w, int h, uint16_t color);
void m5u_display_draw_circle_at(int index, int x, int y, int r, uint16_t color);
void m5u_display_fill_circle_at(int index, int x, int y, int r, uint16_t color);
void m5u_display_write_pixel_at(int index, int x, int y, uint16_t color);
void m5u_display_draw_pixel_at(int index, int x, int y, uint16_t color);
void m5u_display_draw_fast_hline_at(int index, int x, int y, int w, uint16_t color);
void m5u_display_write_fast_hline_at(int index, int x, int y, int w, uint16_t color);
void m5u_display_draw_fast_vline_at(int index, int x, int y, int h, uint16_t color);
void m5u_display_write_fast_vline_at(int index, int x, int y, int h, uint16_t color);
void m5u_display_draw_round_rect_at(int index, int x, int y, int w, int h, int r, uint16_t color);
void m5u_display_fill_round_rect_at(int index, int x, int y, int w, int h, int r, uint16_t color);
void m5u_display_draw_triangle_at(int index, int x0, int y0, int x1, int y1, int x2, int y2, uint16_t color);
void m5u_display_fill_triangle_at(int index, int x0, int y0, int x1, int y1, int x2, int y2, uint16_t color);
void m5u_display_draw_ellipse_at(int index, int x, int y, int rx, int ry, uint16_t color);
void m5u_display_fill_ellipse_at(int index, int x, int y, int rx, int ry, uint16_t color);
void m5u_display_draw_arc_at(int index, int x, int y, int r0, int r1, float angle0, float angle1, uint16_t color);
void m5u_display_fill_arc_at(int index, int x, int y, int r0, int r1, float angle0, float angle1, uint16_t color);
void m5u_display_draw_ellipse_arc_at(int index, int x, int y, int r0x, int r1x, int r0y, int r1y, float angle0, float angle1, uint16_t color);
void m5u_display_fill_ellipse_arc_at(int index, int x, int y, int r0x, int r1x, int r0y, int r1y, float angle0, float angle1, uint16_t color);
void m5u_display_draw_bezier3_at(int index, int x0, int y0, int x1, int y1, int x2, int y2, uint16_t color);
void m5u_display_draw_bezier4_at(int index, int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3, uint16_t color);
void m5u_display_draw_smooth_line_at(int index, int x0, int y0, int x1, int y1, uint16_t color);
void m5u_display_draw_wide_line_at(int index, int x0, int y0, int x1, int y1, float radius, uint16_t color);
void m5u_display_draw_wedge_line_at(int index, int x0, int y0, int x1, int y1, float r0, float r1, uint16_t color);
void m5u_display_draw_gradient_line_at(int index, int x0, int y0, int x1, int y1, uint16_t start_color, uint16_t end_color);
void m5u_display_draw_spot_at(int index, int x, int y, float radius, uint16_t color);
void m5u_display_fill_smooth_circle_at(int index, int x, int y, int r, uint16_t color);
void m5u_display_fill_smooth_round_rect_at(int index, int x, int y, int w, int h, int r, uint16_t color);
void m5u_display_fill_gradient_rect_at(int index, int x, int y, int w, int h, uint16_t start_color, uint16_t end_color, int style);
void m5u_display_flood_fill_at(int index, int x, int y, uint16_t color);
void m5u_display_set_scroll_rect_at(int index, int x, int y, int w, int h);
void m5u_display_set_scroll_rect_color_at(int index, int x, int y, int w, int h, uint16_t color);
void m5u_display_get_scroll_rect_at(int index, int* x, int* y, int* w, int* h);
void m5u_display_clear_scroll_rect_at(int index);
void m5u_display_scroll_at(int index, int dx, int dy);
int m5u_display_text_width_at(int index, const char* text);
int m5u_display_text_length_at(int index, const char* text, int width);
int m5u_display_get_text_datum_at(int index);
int m5u_display_font_width_at(int index);
void m5u_display_set_text_padding_at(int index, uint32_t padding);
uint32_t m5u_display_get_text_padding_at(int index);
float m5u_display_get_text_size_x_at(int index);
float m5u_display_get_text_size_y_at(int index);
void m5u_display_set_clip_rect_at(int index, int x, int y, int w, int h);
void m5u_display_get_clip_rect_at(int index, int* x, int* y, int* w, int* h);
void m5u_display_clear_clip_rect_at(int index);
void m5u_display_set_pivot_at(int index, float x, float y);
float m5u_display_get_pivot_x_at(int index);
float m5u_display_get_pivot_y_at(int index);
bool m5u_display_push_image_rgb565_at(int index, int x, int y, int w, int h, const uint16_t* data);
bool m5u_display_push_image_rgb565_transparent_at(int index, int x, int y, int w, int h, const uint16_t* data, uint16_t transparent);
uint16_t m5u_display_read_pixel_at(int index, int x, int y);
bool m5u_display_read_rect_rgb565_at(int index, int x, int y, int w, int h, uint16_t* data);
void m5u_display_copy_rect_at(int index, int dst_x, int dst_y, int w, int h, int src_x, int src_y);
bool m5u_display_draw_image_at(int index, int format, const uint8_t* data, size_t len, const m5u_image_options_t* options);
bool m5u_display_draw_image_file_at(int index, int format, const char* path, const m5u_image_options_t* options);
void m5u_display_qrcode_at(int index, const char* text, int x, int y, int width, uint8_t version, bool margin);

bool m5u_btn_a_is_pressed(void);
bool m5u_btn_a_was_pressed(void);
bool m5u_btn_a_was_released(void);
bool m5u_btn_b_is_pressed(void);
bool m5u_btn_b_was_pressed(void);
bool m5u_btn_b_was_released(void);
bool m5u_btn_c_is_pressed(void);
bool m5u_btn_c_was_pressed(void);
bool m5u_btn_c_was_released(void);
bool m5u_button_is_pressed(int button);
bool m5u_button_was_pressed(int button);
bool m5u_button_was_released(int button);
bool m5u_button_was_clicked(int button);
bool m5u_button_was_hold(int button);
bool m5u_button_is_holding(int button);
bool m5u_button_was_decide_click_count(int button);
int m5u_button_get_click_count(int button);
bool m5u_button_was_single_clicked(int button);
bool m5u_button_was_double_clicked(int button);
bool m5u_button_was_change_pressed(int button);
bool m5u_button_is_released(int button);
bool m5u_button_was_released_after_hold(int button);
bool m5u_button_was_release_for(int button, uint32_t ms);
bool m5u_button_pressed_for(int button, uint32_t ms);
bool m5u_button_released_for(int button, uint32_t ms);
void m5u_button_set_debounce_thresh(int button, uint32_t ms);
void m5u_button_set_hold_thresh(int button, uint32_t ms);
void m5u_button_set_raw_state(int button, uint32_t msec, bool press);
void m5u_button_set_state(int button, uint32_t msec, uint8_t state);
uint8_t m5u_button_get_state(int button);
uint32_t m5u_button_last_change(int button);
uint32_t m5u_button_get_debounce_thresh(int button);
uint32_t m5u_button_get_hold_thresh(int button);
uint32_t m5u_button_get_update_msec(int button);

typedef struct {
    int pin_data_in;
    int pin_bck;
    int pin_mck;
    int pin_ws;
    uint32_t sample_rate;
    uint8_t left_channel;
    uint8_t stereo;
    uint8_t over_sampling;
    uint8_t magnification;
    uint8_t noise_filter_level;
    uint8_t use_adc;
    size_t dma_buf_len;
    size_t dma_buf_count;
    uint8_t task_priority;
    uint8_t task_pinned_core;
    int i2s_port;
} m5u_mic_config_t;

typedef struct {
    int pin_data_out;
    int pin_bck;
    int pin_mck;
    int pin_ws;
    uint32_t sample_rate;
    uint8_t stereo;
    uint8_t buzzer;
    uint8_t use_dac;
    uint8_t dac_zero_level;
    uint8_t magnification;
    size_t dma_buf_len;
    size_t dma_buf_count;
    uint8_t task_priority;
    uint8_t task_pinned_core;
    int i2s_port;
} m5u_speaker_config_t;

bool m5u_mic_begin(void);
bool m5u_mic_is_running(void);
bool m5u_mic_is_enabled(void);
bool m5u_mic_is_recording(void);
size_t m5u_mic_recording_state(void);
void m5u_mic_end(void);
bool m5u_mic_record_i16(int16_t* buffer, size_t samples);
bool m5u_mic_record_i16_at(int16_t* buffer, size_t samples, uint32_t sample_rate_hz);
bool m5u_mic_record_i16_ex(int16_t* buffer, size_t samples, uint32_t sample_rate_hz, bool stereo);
bool m5u_mic_record_u8(uint8_t* buffer, size_t samples);
bool m5u_mic_record_u8_ex(uint8_t* buffer, size_t samples, uint32_t sample_rate_hz, bool stereo);
bool m5u_audio_capture_begin(uint32_t sample_rate_hz, size_t dma_frame_num, size_t dma_desc_num, uint8_t* out_channels);
size_t m5u_audio_capture_read_i16(int16_t* buffer, size_t samples, uint32_t timeout_ms);
void m5u_audio_capture_end(void);
void m5u_mic_set_sample_rate(uint32_t sample_rate_hz);
bool m5u_mic_get_config(m5u_mic_config_t* out);
bool m5u_mic_set_config(const m5u_mic_config_t* config);
int m5u_mic_get_noise_filter_level(void);
bool m5u_mic_set_noise_filter_level(int level);
bool m5u_speaker_begin(void);
bool m5u_speaker_is_running(void);
bool m5u_speaker_is_enabled(void);
void m5u_speaker_end(void);
void m5u_speaker_set_volume(uint8_t volume);
uint8_t m5u_speaker_get_volume(void);
bool m5u_speaker_get_config(m5u_speaker_config_t* out);
bool m5u_speaker_set_config(const m5u_speaker_config_t* config);
bool m5u_speaker_tone(uint32_t frequency_hz, uint32_t duration_ms);
bool m5u_speaker_tone_ex(float frequency_hz, uint32_t duration_ms, int channel);
bool m5u_speaker_tone_options(float frequency_hz, uint32_t duration_ms, int channel, bool stop_current_sound);
bool m5u_speaker_tone_full(float frequency_hz, uint32_t duration_ms, int channel, bool stop_current_sound, const uint8_t* raw_data, size_t len, bool stereo);
bool m5u_speaker_play_i16(const int16_t* samples, size_t len, uint32_t sample_rate_hz);
bool m5u_speaker_play_i16_ex(const int16_t* samples, size_t len, uint32_t sample_rate_hz, bool stereo, uint32_t repeat, int channel, bool stop_current_sound);
bool m5u_speaker_play_i8_ex(const int8_t* samples, size_t len, uint32_t sample_rate_hz, bool stereo, uint32_t repeat, int channel, bool stop_current_sound);
bool m5u_speaker_play_u8(const uint8_t* samples, size_t len, uint32_t sample_rate_hz);
bool m5u_speaker_play_u8_ex(const uint8_t* samples, size_t len, uint32_t sample_rate_hz, bool stereo, uint32_t repeat, int channel, bool stop_current_sound);
bool m5u_speaker_play_wav(const uint8_t* data, size_t len);
bool m5u_speaker_play_wav_ex(const uint8_t* data, size_t len, uint32_t repeat, int channel, bool stop_current_sound);
bool m5u_speaker_is_playing(int channel);
size_t m5u_speaker_playing_channels(void);
size_t m5u_speaker_channel_playing_state(int channel);
void m5u_speaker_stop(int channel);
uint8_t m5u_speaker_get_channel_volume(int channel);
void m5u_speaker_set_channel_volume(int channel, uint8_t volume);
void m5u_speaker_set_all_channel_volume(uint8_t volume);

typedef struct {
    uint32_t usec;
    float accel_x;
    float accel_y;
    float accel_z;
    float gyro_x;
    float gyro_y;
    float gyro_z;
    float mag_x;
    float mag_y;
    float mag_z;
} m5u_imu_data_t;

typedef struct {
    int16_t accel_x;
    int16_t accel_y;
    int16_t accel_z;
    int16_t gyro_x;
    int16_t gyro_y;
    int16_t gyro_z;
    int16_t mag_x;
    int16_t mag_y;
    int16_t mag_z;
    int16_t temp;
    uint8_t sensor_mask;
} m5u_imu_raw_data_t;

typedef struct {
    float accel_res;
    float gyro_res;
    float mag_res;
    float temp_res;
    float temp_offset;
} m5u_imu_convert_param_t;

bool m5u_imu_begin(void);
bool m5u_imu_begin_for_board(int board);
bool m5u_imu_is_enabled(void);
int m5u_imu_get_type(void);
bool m5u_imu_update(void);
int m5u_imu_update_mask(void);
bool m5u_imu_sleep(void);
void m5u_imu_set_clock(uint32_t freq);
bool m5u_imu_set_axis_order(int axis0, int axis1, int axis2);
bool m5u_imu_set_axis_order_right_handed(int axis0, int axis1);
bool m5u_imu_set_axis_order_left_handed(int axis0, int axis1);
bool m5u_imu_set_int_pin_active_logic(bool level);
bool m5u_imu_get_accel(float* x, float* y, float* z);
bool m5u_imu_get_gyro(float* x, float* y, float* z);
bool m5u_imu_get_mag(float* x, float* y, float* z);
bool m5u_imu_get_data(m5u_imu_data_t* out);
bool m5u_imu_get_temp_c(float* temp);
bool m5u_imu_load_offset_from_nvs(void);
bool m5u_imu_save_offset_to_nvs(void);
float m5u_imu_get_offset_data(int index);
void m5u_imu_set_calibration(float x, float y, float z);
void m5u_imu_set_calibration_strength(uint8_t accel, uint8_t gyro, uint8_t mag);
void m5u_imu_clear_offset_data(void);
void m5u_imu_set_offset_data(size_t index, int32_t value);
int32_t m5u_imu_get_offset_data_i32(size_t index);
int16_t m5u_imu_get_raw_data(size_t index);
int m5u_imu_device_begin(int kind);
bool m5u_imu_device_get_raw_data(int kind, m5u_imu_raw_data_t* out);
bool m5u_imu_device_get_convert_param(int kind, m5u_imu_convert_param_t* out);
bool m5u_imu_device_get_temp_adc(int kind, int16_t* adc);
bool m5u_imu_device_sleep(int kind);
bool m5u_imu_device_set_int_pin_active_logic(int kind, bool level);
int m5u_imu_device_who_am_i(int kind);

typedef struct {
    int x;
    int y;
    int prev_x;
    int prev_y;
    int base_x;
    int base_y;
    uint32_t base_msec;
    uint8_t state;
    bool is_pressed;
    bool was_pressed;
    bool was_released;
    bool was_clicked;
    bool was_hold;
    bool is_holding;
    int click_count;
} m5u_touch_detail_t;

int m5u_touch_count(void);
bool m5u_touch_get(int index, int* x, int* y);
bool m5u_touch_get_raw(int index, int* x, int* y);
bool m5u_touch_get_detail(int index, m5u_touch_detail_t* out);
bool m5u_touch_is_enabled(void);
void m5u_touch_set_hold_thresh(uint16_t ms);
void m5u_touch_set_flick_thresh(uint16_t distance);

typedef struct {
    int year;
    int month;
    int day;
    int weekday;
    int hour;
    int minute;
    int second;
} m5u_rtc_datetime_t;

bool m5u_rtc_begin(void);
bool m5u_rtc_begin_for_board(int board);
bool m5u_rtc_is_enabled(void);
bool m5u_rtc_get_volt_low(void);
bool m5u_rtc_get_datetime(int* year, int* month, int* day, int* hour, int* minute, int* second);
bool m5u_rtc_get_datetime_detail(m5u_rtc_datetime_t* out);
bool m5u_rtc_get_date_detail(m5u_rtc_datetime_t* out);
bool m5u_rtc_get_time_detail(m5u_rtc_datetime_t* out);
bool m5u_rtc_set_datetime(int year, int month, int day, int hour, int minute, int second);
bool m5u_rtc_set_datetime_detail(const m5u_rtc_datetime_t* datetime);
bool m5u_rtc_set_date_detail(const m5u_rtc_datetime_t* date);
bool m5u_rtc_set_time_detail(const m5u_rtc_datetime_t* time);
void m5u_rtc_set_system_time_from_rtc(void);
uint32_t m5u_rtc_set_timer_irq(uint32_t timer_msec);
int m5u_rtc_set_alarm_irq_after_seconds(int after_seconds);
int m5u_rtc_set_alarm_irq_datetime(const m5u_rtc_datetime_t* datetime);
int m5u_rtc_set_alarm_irq_time(const m5u_rtc_datetime_t* time);
bool m5u_rtc_get_irq_status(void);
void m5u_rtc_clear_irq(void);
void m5u_rtc_disable_irq(void);
bool m5u_rtc_device_begin(int kind);
bool m5u_rtc_device_get_datetime_detail(int kind, m5u_rtc_datetime_t* out);
bool m5u_rtc_device_get_date_detail(int kind, m5u_rtc_datetime_t* out);
bool m5u_rtc_device_get_time_detail(int kind, m5u_rtc_datetime_t* out);
bool m5u_rtc_device_set_datetime_detail(int kind, const m5u_rtc_datetime_t* datetime);
bool m5u_rtc_device_set_date_detail(int kind, const m5u_rtc_datetime_t* date);
bool m5u_rtc_device_set_time_detail(int kind, const m5u_rtc_datetime_t* time);
bool m5u_rtc_device_get_volt_low(int kind);
uint32_t m5u_rtc_device_set_timer_irq(int kind, uint32_t timer_msec);
int m5u_rtc_device_set_alarm_irq_datetime(int kind, const m5u_rtc_datetime_t* datetime);
int m5u_rtc_device_set_alarm_irq_time(int kind, const m5u_rtc_datetime_t* time);
bool m5u_rtc_device_get_irq_status(int kind);
void m5u_rtc_device_clear_irq(int kind);
void m5u_rtc_device_disable_irq(int kind);

int m5u_battery_level(void);
int m5u_battery_voltage_mv(void);
typedef struct {
    uint16_t voltage_mv;
    uint8_t current_limit_ma;
    bool enable;
    bool direction_output;
} m5u_power_ext_port_bus_t;
typedef struct {
    float shunt_res;
    float max_expected_current;
    uint8_t sampling_rate;
    uint8_t shunt_conversion_time;
    uint8_t bus_conversion_time;
    uint8_t mode;
} m5u_power_ina226_config_t;
bool m5u_power_begin(void);
int m5u_power_get_type(void);
int m5u_power_get_charge_state(void);
bool m5u_power_is_charging(void);
void m5u_power_set_led(uint8_t brightness);
void m5u_power_set_ext_output(bool enable, uint16_t port_mask);
bool m5u_power_get_ext_output(void);
void m5u_power_set_usb_output(bool enable);
bool m5u_power_get_usb_output(void);
void m5u_power_set_battery_charge(bool enable);
void m5u_power_set_charge_current(uint16_t max_ma);
void m5u_power_set_charge_voltage(uint16_t max_mv);
int m5u_power_get_vbus_voltage_mv(void);
int m5u_power_get_battery_current_ma(void);
float m5u_power_get_ext_voltage_mv(uint16_t port_mask);
float m5u_power_get_ext_current_ma(uint16_t port_mask);
uint8_t m5u_power_get_key_state(void);
void m5u_power_set_ext_port_bus_config(const m5u_power_ext_port_bus_t* config);
void m5u_power_set_vibration(uint8_t level);
void m5u_power_power_off(void);
void m5u_power_timer_sleep_seconds(int seconds);
void m5u_power_timer_sleep_time(const m5u_rtc_datetime_t* time);
void m5u_power_timer_sleep_date_time(const m5u_rtc_datetime_t* date, const m5u_rtc_datetime_t* time);
void m5u_power_deep_sleep_us(uint64_t micro_seconds, bool touch_wakeup);
void m5u_power_light_sleep_us(uint64_t micro_seconds, bool touch_wakeup);
bool m5u_power_axp192_begin(void);
int m5u_power_axp192_get_battery_level(void);
bool m5u_power_axp192_set_battery_charge(bool enable);
bool m5u_power_axp192_set_charge_current(uint16_t max_ma);
bool m5u_power_axp192_set_charge_voltage(uint16_t max_mv);
bool m5u_power_axp192_is_charging(void);
bool m5u_power_axp192_set_dcdc(uint8_t channel, int voltage_mv);
bool m5u_power_axp192_set_ldo(uint8_t channel, int voltage_mv);
bool m5u_power_axp192_set_gpio(uint8_t gpio_num, bool state);
bool m5u_power_axp192_power_off(void);
bool m5u_power_axp192_set_adc_state(bool enable);
bool m5u_power_axp192_set_adc_rate(uint8_t rate);
bool m5u_power_axp192_set_exten(bool enable);
bool m5u_power_axp192_set_backup(bool enable);
bool m5u_power_axp192_is_acin(void);
bool m5u_power_axp192_is_vbus(void);
bool m5u_power_axp192_get_bat_state(void);
bool m5u_power_axp192_get_exten(void);
float m5u_power_axp192_get_battery_voltage_v(void);
float m5u_power_axp192_get_battery_discharge_current_ma(void);
float m5u_power_axp192_get_battery_charge_current_ma(void);
float m5u_power_axp192_get_battery_power_mw(void);
float m5u_power_axp192_get_acin_voltage_v(void);
float m5u_power_axp192_get_acin_current_ma(void);
float m5u_power_axp192_get_vbus_voltage_v(void);
float m5u_power_axp192_get_vbus_current_ma(void);
float m5u_power_axp192_get_aps_voltage_v(void);
float m5u_power_axp192_get_internal_temperature_c(void);
uint8_t m5u_power_axp192_get_pek_press(void);
bool m5u_power_aw32001_begin(void);
bool m5u_power_aw32001_set_battery_charge(bool enable);
bool m5u_power_aw32001_set_charge_current(uint16_t max_ma);
bool m5u_power_aw32001_set_charge_voltage(uint16_t max_mv);
bool m5u_power_aw32001_is_charging(void);
uint16_t m5u_power_aw32001_get_charge_current(void);
uint16_t m5u_power_aw32001_get_charge_voltage(void);
int m5u_power_aw32001_get_charge_status(void);
bool m5u_power_bq27220_begin(void);
int16_t m5u_power_bq27220_get_current_ma(void);
int16_t m5u_power_bq27220_get_voltage_mv(void);
float m5u_power_bq27220_get_current_a(void);
float m5u_power_bq27220_get_voltage_v(void);
bool m5u_power_ina226_begin(void);
bool m5u_power_ina226_config(const m5u_power_ina226_config_t* config);
float m5u_power_ina226_get_bus_voltage_v(void);
float m5u_power_ina226_get_shunt_voltage_v(void);
float m5u_power_ina226_get_shunt_current_a(void);
float m5u_power_ina226_get_power_w(void);
bool m5u_power_ina3221_begin(size_t index);
float m5u_power_ina3221_get_bus_voltage_v(size_t index, uint8_t channel);
float m5u_power_ina3221_get_shunt_voltage_v(size_t index, uint8_t channel);
float m5u_power_ina3221_get_current_a(size_t index, uint8_t channel);
int32_t m5u_power_ina3221_get_bus_voltage_mv(size_t index, uint8_t channel);
int32_t m5u_power_ina3221_get_shunt_voltage_mv(size_t index, uint8_t channel);
bool m5u_power_ina3221_set_shunt_res(size_t index, uint8_t channel, uint32_t res);
bool m5u_power_ip5306_begin(void);
int m5u_power_ip5306_get_battery_level(void);
bool m5u_power_ip5306_set_battery_charge(bool enable);
bool m5u_power_ip5306_set_charge_current(uint16_t max_ma);
bool m5u_power_ip5306_set_charge_voltage(uint16_t max_mv);
bool m5u_power_ip5306_is_charging(void);
bool m5u_power_ip5306_set_power_boost_keep_on(bool enable);
bool m5u_power_py32pmic_begin(void);
bool m5u_power_py32pmic_set_ext_output(bool enable);
bool m5u_power_py32pmic_set_battery_charge(bool enable);
bool m5u_power_py32pmic_set_charge_current(uint16_t max_ma);
bool m5u_power_py32pmic_set_charge_voltage(uint16_t max_mv);
bool m5u_power_py32pmic_is_charging(void);
uint16_t m5u_power_py32pmic_get_charge_current(void);
uint16_t m5u_power_py32pmic_get_charge_voltage(void);
uint8_t m5u_power_py32pmic_get_pek_press(void);
bool m5u_power_py32pmic_power_off(void);
bool m5u_power_axp2101_begin(void);
int m5u_power_axp2101_get_battery_level(void);
bool m5u_power_axp2101_set_battery_charge(bool enable);
bool m5u_power_axp2101_set_pre_charge_current(uint16_t max_ma);
bool m5u_power_axp2101_set_charge_current(uint16_t max_ma);
bool m5u_power_axp2101_set_charge_voltage(uint16_t max_mv);
int m5u_power_axp2101_get_charge_status(void);
bool m5u_power_axp2101_is_charging(void);
bool m5u_power_axp2101_set_ldo(int kind, int channel, int voltage_mv);
bool m5u_power_axp2101_get_ldo_enabled(int kind, int channel);
bool m5u_power_axp2101_power_off(void);
bool m5u_power_axp2101_set_adc_state(bool enable);
bool m5u_power_axp2101_set_adc_rate(uint8_t rate);
bool m5u_power_axp2101_set_backup(bool enable);
bool m5u_power_axp2101_is_acin(void);
bool m5u_power_axp2101_is_vbus(void);
bool m5u_power_axp2101_get_bat_state(void);
float m5u_power_axp2101_get_battery_voltage_v(void);
float m5u_power_axp2101_get_battery_discharge_current_ma(void);
float m5u_power_axp2101_get_battery_charge_current_ma(void);
float m5u_power_axp2101_get_battery_power_mw(void);
float m5u_power_axp2101_get_acin_voltage_v(void);
float m5u_power_axp2101_get_acin_current_ma(void);
float m5u_power_axp2101_get_vbus_voltage_v(void);
float m5u_power_axp2101_get_vbus_current_ma(void);
float m5u_power_axp2101_get_ts_voltage_v(void);
float m5u_power_axp2101_get_aps_voltage_v(void);
float m5u_power_axp2101_get_internal_temperature_c(void);
uint8_t m5u_power_axp2101_get_pek_press(void);
bool m5u_power_axp2101_disable_irq(uint64_t mask);
bool m5u_power_axp2101_enable_irq(uint64_t mask);
bool m5u_power_axp2101_clear_irq_statuses(void);
uint64_t m5u_power_axp2101_get_irq_statuses(void);
bool m5u_power_axp2101_is_bat_charger_under_temperature_irq(void);
bool m5u_power_axp2101_is_bat_charger_over_temperature_irq(void);
bool m5u_power_axp2101_is_vbus_insert_irq(void);
bool m5u_power_axp2101_is_vbus_remove_irq(void);

typedef struct {
    uint8_t r;
    uint8_t g;
    uint8_t b;
} m5u_led_color_t;
typedef struct {
    size_t led_count;
    int color_order;
    uint8_t byte_per_led;
} m5u_led_strip_config_t;
typedef struct {
    uint32_t frequency;
    uint16_t t0h_ns;
    uint16_t t0l_ns;
    uint16_t t1h_ns;
    uint16_t t1l_ns;
    uint16_t reset_us;
    int8_t pin_data;
} m5u_led_strip_rmt_config_t;
bool m5u_led_begin(void);
void m5u_led_display(void);
void m5u_led_set_auto_display(bool enable);
size_t m5u_led_count(void);
void m5u_led_set_brightness(uint8_t brightness);
void m5u_led_set_color_rgb(size_t index, uint8_t r, uint8_t g, uint8_t b);
void m5u_led_set_all_color_rgb(uint8_t r, uint8_t g, uint8_t b);
void m5u_led_set_colors_rgb(const m5u_led_color_t* colors, size_t index, size_t length);
int m5u_led_get_type(size_t index);
bool m5u_led_is_enabled(void);
bool m5u_led_power_hub_begin(void);
size_t m5u_led_power_hub_count(void);
void m5u_led_power_hub_set_brightness(uint8_t brightness);
void m5u_led_power_hub_set_color_rgb(size_t index, uint8_t r, uint8_t g, uint8_t b);
void m5u_led_power_hub_set_colors_rgb(const m5u_led_color_t* colors, size_t index, size_t length);
void m5u_led_power_hub_display(void);
int m5u_led_power_hub_get_type(size_t index);
bool m5u_led_strip_set_config(const m5u_led_strip_config_t* config);
bool m5u_led_strip_set_rmt_bus_config(const m5u_led_strip_rmt_config_t* config);
bool m5u_led_strip_begin(void);
size_t m5u_led_strip_count(void);
void m5u_led_strip_set_brightness(uint8_t brightness);
void m5u_led_strip_set_color_rgb(size_t index, uint8_t r, uint8_t g, uint8_t b);
void m5u_led_strip_set_colors_rgb(const m5u_led_color_t* colors, size_t index, size_t length);
void m5u_led_strip_display(void);
int m5u_led_strip_get_type(size_t index);

void m5u_log_print(const char* text);
void m5u_log_println(const char* text);
void m5u_log_println_empty(void);
void m5u_log_level(int level, const char* text);
void m5u_log_dump(const void* addr, uint32_t len, int level);
const char* m5u_log_path_to_file_name(const char* path);
typedef void (*m5u_log_callback_t)(int level, bool use_color, const char* text, void* user_data);
bool m5u_log_set_callback(m5u_log_callback_t callback, void* user_data);
bool m5u_log_set_enable_color(int target, bool enable);
bool m5u_log_get_enable_color(int target);
bool m5u_log_set_level(int target, int level);
int m5u_log_get_level(int target);
bool m5u_log_set_suffix(int target, const char* suffix);

typedef struct {
    int pin_sclk;
    int pin_mosi;
    int pin_miso;
    int pin_cs;
    int host_id;
    uint32_t frequency_khz;
    int max_files;
    uint8_t format_if_mount_failed;
} m5u_sd_spi_config_t;

bool m5u_sd_begin(void);
bool m5u_sd_begin_spi(const m5u_sd_spi_config_t* config);
bool m5u_sd_is_mounted(void);
void m5u_sd_end(void);

#define M5U_CARDPUTER_KEYBOARD_WORD_CAPACITY 32
#define M5U_CARDPUTER_KEYBOARD_HID_CAPACITY 32
#define M5U_CARDPUTER_KEYBOARD_MODIFIER_CAPACITY 8

typedef struct {
    bool tab;
    bool fn_key;
    bool shift;
    bool ctrl;
    bool opt;
    bool alt;
    bool del;
    bool enter;
    bool space;
    uint8_t modifiers;
    size_t word_len;
    uint8_t word[M5U_CARDPUTER_KEYBOARD_WORD_CAPACITY];
    size_t hid_len;
    uint8_t hid_keys[M5U_CARDPUTER_KEYBOARD_HID_CAPACITY];
    size_t modifier_len;
    uint8_t modifier_keys[M5U_CARDPUTER_KEYBOARD_MODIFIER_CAPACITY];
} m5u_cardputer_keyboard_state_t;

typedef struct {
    uint8_t first;
    uint8_t second;
} m5u_cardputer_key_value_t;

bool m5u_cardputer_begin(bool enable_keyboard);
bool m5u_cardputer_begin_with_config(const m5u_config_t* config, bool enable_keyboard);
void m5u_cardputer_update(void);
void m5u_cardputer_keyboard_begin(void);
bool m5u_cardputer_keyboard_is_pressed(void);
uint8_t m5u_cardputer_keyboard_pressed_count(void);
bool m5u_cardputer_keyboard_is_change(void);
bool m5u_cardputer_keyboard_is_key_pressed(uint8_t key);
uint8_t m5u_cardputer_keyboard_get_key(uint8_t x, uint8_t y);
bool m5u_cardputer_keyboard_get_key_value(uint8_t x, uint8_t y, m5u_cardputer_key_value_t* out);
bool m5u_cardputer_keyboard_get_state(m5u_cardputer_keyboard_state_t* out);
bool m5u_cardputer_keyboard_capslocked(void);
void m5u_cardputer_keyboard_set_capslocked(bool locked);
bool m5u_cardputer_ir_begin(int pin);
bool m5u_cardputer_ir_send_nec(uint16_t address, uint8_t command, uint8_t repeats);
bool m5u_cardputer_grove_i2c_begin(int sda, int scl, uint32_t frequency_hz);
void m5u_cardputer_grove_i2c_end(void);
bool m5u_cardputer_grove_i2c_probe(uint8_t address);
bool m5u_cardputer_grove_i2c_write(uint8_t address, const uint8_t* data, size_t len);
size_t m5u_cardputer_grove_i2c_read(uint8_t address, uint8_t* data, size_t len);
bool m5u_cardputer_grove_gpio_pin_mode(int pin, int mode);
bool m5u_cardputer_grove_gpio_write(int pin, bool high);
int m5u_cardputer_grove_gpio_read(int pin);
bool m5u_cardputer_grove_uart_begin(int rx, int tx, uint32_t baud);
void m5u_cardputer_grove_uart_end(void);
size_t m5u_cardputer_grove_uart_available(void);
size_t m5u_cardputer_grove_uart_read(uint8_t* data, size_t len);
size_t m5u_cardputer_grove_uart_write(const uint8_t* data, size_t len);
void m5u_cardputer_grove_uart_flush(void);

// Off-screen canvas (LGFX_Sprite) — draw everything here, then push to display
// in one DMA transfer to eliminate per-primitive flicker.

bool m5u_canvas_create(int width, int height);
void m5u_canvas_push(int x, int y);
void m5u_canvas_delete(void);
void m5u_canvas_fill_screen(uint16_t color);
void m5u_canvas_fill_smooth_circle(int x, int y, int r, uint16_t color);
void m5u_canvas_draw_line(int x0, int y0, int x1, int y1, uint16_t color);
void m5u_canvas_draw_circle(int x, int y, int r, uint16_t color);
void m5u_canvas_fill_circle(int x, int y, int r, uint16_t color);
void m5u_canvas_fill_rect(int x, int y, int w, int h, uint16_t color);
void m5u_canvas_fill_triangle(int x0, int y0, int x1, int y1, int x2, int y2, uint16_t color);
void m5u_canvas_fill_smooth_round_rect(int x, int y, int w, int h, int r, uint16_t color);
void m5u_canvas_fill_arc(int x, int y, int r0, int r1, float a0, float a1, uint16_t color);
void m5u_canvas_fill_ellipse(int x, int y, int rx, int ry, uint16_t color);
void m5u_canvas_draw_ellipse(int x, int y, int rx, int ry, uint16_t color);
void m5u_canvas_set_text_size(int size);
void m5u_canvas_set_text_color(uint16_t fg, uint16_t bg);
void m5u_canvas_set_text_datum(int datum);
int m5u_canvas_text_width(const char* text);
int m5u_canvas_draw_string(const char* text, int x, int y);

// FEETECH SCSCL bus servo control (StackChan head servos)
// Uses ESP-IDF UART driver. On non-firmware (host stub) builds these are no-ops.
// Servo IDs: 1 = yaw (left/right), 2 = pitch (up/down)
// Default pins for M5Stack Core S3: TX=6, RX=7, baud=1000000

// Initialize the FEETECH servo UART bus.
// Pass -1 for tx_pin/rx_pin/baud_rate to use StackChan Core S3 defaults (TX=6, RX=7, 1Mbps).
bool m5u_servo_init(int tx_pin, int rx_pin, int baud_rate);

// Write goal position to a SCSCL servo.
// raw_pos: raw position units (0–1023)
// time_ms: travel duration in milliseconds (0 = fastest)
// speed:   max speed limit (0–1023, 0 = no limit)
bool m5u_servo_write_raw_pos(uint8_t id, uint16_t raw_pos, uint16_t time_ms, uint16_t speed);

// Read current raw position from a SCSCL servo (returns -1 on timeout / error).
int m5u_servo_read_raw_pos(uint8_t id);

// Enable or disable torque for a servo.
bool m5u_servo_enable_torque(uint8_t id, bool enable);

// Deinitialize and release the servo UART bus.
void m5u_servo_deinit(void);

// NVS (non-volatile storage) helpers — thin wrappers around esp_nvs to persist
// calibration data across reboots.  On host stub builds these are no-ops.
bool m5u_nvs_read_i32(const char* ns, const char* key, int32_t* out_val);
bool m5u_nvs_write_i32(const char* ns, const char* key, int32_t val);

#ifdef __cplusplus
}
#endif
