[package]
name = "m5remote-rust-poc"
version = "0.1.0"
edition = "2021"
resolver = "2"
publish = false

[[bin]]
name = "m5remote-rust-poc"
path = "src/main.rs"

[dependencies]
m5unified = "0.3"

[target.'cfg(target_os = "espidf")'.dependencies]
esp-idf-sys = { version = "0.37.2", default-features = false, features = ["std", "binstart"] }

[build-dependencies]
embuild = { version = "0.33", features = ["espidf"] }

[package.metadata.esp-idf-sys]
esp_idf_version = "v5.3.2"

[[package.metadata.esp-idf-sys.extra_components]]
component_dirs = ["components"]

[profile.release]
opt-level = "s"

[profile.dev]
debug = true
opt-level = "z"
