[platformio]
default_envs = core2aws

[env:core2aws]
platform = espressif32
board = m5stack-core2
framework = arduino
monitor_speed = 115200
lib_deps =
  m5stack/M5Unified
  marian-craciunescu/ESP32Ping
  bblanchon/ArduinoJson
build_flags =
  -DCORE_DEBUG_LEVEL=3
